"""Journal: add date_created column

Revision ID: 0f01249f9dcd
Revises: 25fa9afcf369
Create Date: 2026-09-14 07:08:18.741116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f01249f9dcd'
down_revision = '25fa9afcf369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
